# Generated by Django 3.0.3 on 2020-05-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200426_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='abcd@ermail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
